//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscribesView
    {
        public int Id { get; set; }
        public int IdSubscriber { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int IdDistrict { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public Nullable<int> Apartment { get; set; }
        public string RegionName { get; set; }
        public string Postman { get; set; }
        public int IdPublications { get; set; }
        public string PubIndex { get; set; }
        public string Title { get; set; }
        public string PubType { get; set; }
        public int Price { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Duration { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    }
}
